### ISSUE TITLE
Sorting and Searching on same column twice

### ISSUE THREAD

**Issue by jmaggesi** [jbox-web/ajax-datatables-rails#173]
Hi to all,
i'm using the gem in the _v-0-4-0_ branch with _Rails 5.0_ but i'm having some problem with the visualization of a Model in my project.

The Models involved:

``` ruby
class Transaction < ApplicationRecord
  belongs_to :seller, :class_name => 'User'
  belongs_to :buyer, :class_name => 'User'
end

class User < ApplicationRecord
  has_many :sales, :class_name => 'Transaction', :foreign_key => 'seller_id'
  has_many :purchases, :class_name => 'Transaction', :foreign_key => 'buyer_id'
end
```

This is the **TransactionDatatables.rb** that i've used:

``` ruby
class TransactionDatatable < AjaxDatatablesRails::Base

  def view_columns
    @view_columns ||= {
      id: { source: 'Transaction.id', searchable: false, orderable: true, cond: :eq },
      seller: { source: 'User.email', searchable: true, orderable: true},
      buyer: { source: 'User.email', searchable: true, orderable: true},
      amount: { source: 'Transaction.amount', searchable: false, orderable: true }
    }
  end

  def data
    records.map do |transaction|
      {
        id: transaction.id,
        seller: transaction.seller.try(:email),
        buyer: transaction.buyer.try(:email),
        amount: transaction.amount
      }
    end
  end

  private

  def get_raw_records
    Transaction.where('accepted' => false).where('rejected' => false).includes(:seller).includes(:buyer).select('transactions.id, amount, seller_id, buyer_id')
  end

end
```

The problem is that when i've tried to perform sorting in the _Seller_ or _Buyer_ column of the table the ordering is performed on the User.email column because my assignments in the **view_columns** method. 

So when the table is shown the first time:

| Seller | Buyer |
| :-: | :-: |
| abc@example.com | zzz@example.com |
| zzz@example.com | abc@example.com |

If i try to sort on the _Seller_ column the result are ordered correctly, but when i try to order by the _Buyer_ column the order is based on the _Seller_ column.

I've tried to assign the _seller_ and _buyer_ value using something like _Transaction.seller.email_ but i've got an error. 

Am i missing something from the documentation ?

**Comment by jmaggesi** [comment]
Actually i think i've found a solution after some changes in the **TransactionDatatables.rb**

I don't know if it's the better solution but seems to work

``` ruby
class TransactionDatatable < AjaxDatatablesRails::Base

  def view_columns
    @view_columns ||= {
      id: { source: 'Transaction.id', searchable: false, orderable: true, cond: :eq },
      seller: { source: 'seller_email', searchable: true, orderable: true},
      buyer: { source: 'buyer_email', searchable: true, orderable: true},
      amount: { source: 'Transaction.amount', searchable: false, orderable: true }
    }
  end

  def data
    records.map do |transaction|
      {
        id: transaction.id,
        seller: transaction[:seller_email],
        buyer: transaction[:buyer_email],
        amount: transaction.amount
      }
    end
  end

  private

  def get_raw_records
    Transaction.joins("LEFT OUTER JOIN users ON users.id = transactions.seller_id")
    .joins("LEFT OUTER JOIN users buyers_transactions ON buyers_transactions.id = transactions.buyer_id")
    .select("transactions.id, amount, seller_id, buyer_id, users.email AS seller_email, buyers_transactions.email AS buyer_email")
    .where.not('share1' => nil).where.not('share2' => nil).where.not('pictureBW' => nil).where.not('pictureOriginal' => nil)
    .where.not('recreatedPic' => nil).where('accepted' => false).where('rejected' => false)
  end

end

```

**Comment by jmaggesi** [comment]
After some testing i've found that using that configuration produce an error when the user try to do a search. The output of the error is this one:

```
wrong constant name seller_email
Extracted source (around line #268):

#266       names.inject(Object) do |constant, name|
#267         if constant == Object
*268           constant.const_get(name)
#269         else
#270           candidate = constant.const_get(name)
#271           next candidate if constant.const_defined?(name, false)

Extracted source (around line #268):

#266       names.inject(Object) do |constant, name|
#267         if constant == Object
*268           constant.const_get(name)
#269         else
#270           candidate = constant.const_get(name)
#271           next candidate if constant.const_defined?(name, false)

Extracted source (around line #266):

#264       names.shift if names.size > 1 && names.first.empty?
#265 
*266       names.inject(Object) do |constant, name|
#267         if constant == Object
#268           constant.const_get(name)
#269         else

```

**Comment by ajahongir** [comment]
@jmaggesi thanks for reporting the problem.
could you send show your SQL query that generated while searching action?

**Comment by jmaggesi** [comment]
@ajahongir actually the gem crashes during the building of the SQL Query generated. 

Seems that has a problem only in the search, the ordering works correctly.

The Framework Trace is:

```
Framework Trace
activesupport (5.0.0) lib/active_support/inflector/methods.rb:268:in `const_get'
activesupport (5.0.0) lib/active_support/inflector/methods.rb:268:in `block in constantize'
activesupport (5.0.0) lib/active_support/inflector/methods.rb:266:in `each'
activesupport (5.0.0) lib/active_support/inflector/methods.rb:266:in `inject'
activesupport (5.0.0) lib/active_support/inflector/methods.rb:266:in `constantize'
activesupport (5.0.0) lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/Users/jonny/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/ajax-datatables-rails-6769547aa032/lib/ajax-datatables-rails/datatable/column.rb:44:in `table'
/Users/jonny/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/ajax-datatables-rails-6769547aa032/lib/ajax-datatables-rails/datatable/column.rb:89:in `non_regex_search'
/Users/jonny/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/ajax-datatables-rails-6769547aa032/lib/ajax-datatables-rails/datatable/column.rb:53:in `search_query'
/Users/jonny/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/ajax-datatables-rails-6769547aa032/lib/ajax-datatables-rails/orm/active_record.rb:41:in `block (2 levels) in build_conditions_for_datatable'
/Users/jonny/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/ajax-datatables-rails-6769547aa032/lib/ajax-datatables-rails/orm/active_record.rb:39:in `map'
/Users/jonny/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/ajax-datatables-rails-6769547aa032/lib/ajax-datatables-rails/orm/active_record.rb:39:in `block in build_conditions_for_datatable'
/Users/jonny/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/ajax-datatables-rails-6769547aa032/lib/ajax-datatables-rails/orm/active_record.rb:37:in `each'
/Users/jonny/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/ajax-datatables-rails-6769547aa032/lib/ajax-datatables-rails/orm/active_record.rb:37:in `inject'
/Users/jonny/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/ajax-datatables-rails-6769547aa032/lib/ajax-datatables-rails/orm/active_record.rb:37:in `build_conditions_for_datatable'
/Users/jonny/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/ajax-datatables-rails-6769547aa032/lib/ajax-datatables-rails/orm/active_record.rb:29:in `build_conditions'
/Users/jonny/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/ajax-datatables-rails-6769547aa032/lib/ajax-datatables-rails/orm/active_record.rb:10:in `filter_records'
/Users/jonny/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/ajax-datatables-rails-6769547aa032/lib/ajax-datatables-rails/base.rb:40:in `as_json'
activesupport (5.0.0) lib/active_support/json/encoding.rb:33:in `encode'
activesupport (5.0.0) lib/active_support/json/encoding.rb:20:in `encode'
activesupport (5.0.0) lib/active_support/core_ext/object/json.rb:37:in `to_json'
actionpack (5.0.0) lib/action_controller/metal/renderers.rb:159:in `block in <module:Renderers>'
actionpack (5.0.0) lib/action_controller/metal/renderers.rb:152:in `block in _render_to_body_with_renderer'
/Users/jonny/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/set.rb:306:in `each_key'
/Users/jonny/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/set.rb:306:in `each'
actionpack (5.0.0) lib/action_controller/metal/renderers.rb:148:in `_render_to_body_with_renderer'
actionpack (5.0.0) lib/action_controller/metal/renderers.rb:144:in `render_to_body'
actionpack (5.0.0) lib/abstract_controller/rendering.rb:26:in `render'
actionpack (5.0.0) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.0.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/jonny/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (5.0.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.0.0) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (5.0.0) lib/action_controller/metal/mime_responds.rb:201:in `respond_to'
actionpack (5.0.0) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.0) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.0) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.0) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.0) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.0) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.0) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.0) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.0) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.0) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.0) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.0) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.0) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.0) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.0) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.0) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.0) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.0) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.0) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.0) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:725:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.0) lib/active_record/migration.rb:552:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.0) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.0) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.3.1) lib/web_console/middleware.rb:131:in `call_app'
web-console (3.3.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.3.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.3.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.1.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
railties (5.0.0) lib/rails/engine.rb:522:in `call'
puma (3.6.0) lib/puma/configuration.rb:225:in `call'
puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
puma (3.6.0) lib/puma/server.rb:415:in `process_client'
puma (3.6.0) lib/puma/server.rb:275:in `block in run'
puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by jmaggesi** [comment]
@ajahongir The SQL generated during the loading of the datatable is:

``` sql
SELECT COUNT(*) 
FROM `transactions` 
LEFT OUTER JOIN users ON users.id = transactions.seller_id 
LEFT OUTER JOIN users buyers_transactions ON buyers_transactions.id = transactions.buyer_id 
WHERE (`transactions`.`share1` IS NOT NULL) AND 
           (`transactions`.`share2` IS NOT NULL) AND 
           (`transactions`.`pictureBW` IS NOT NULL) AND 
           (`transactions`.`pictureOriginal` IS NOT NULL) AND 
           (`transactions`.`recreatedPic` IS NOT NULL) AND 
          `transactions`.`accepted` = 0 AND 
          `transactions`.`rejected` = 0
```

The second one:

``` sql
SELECT COUNT(*) 
FROM (
         SELECT transactions.id, amount, seller_id, buyer_id, users.email AS seller_email, buyers_transactions.email AS buyer_email 
         FROM `transactions` 
         LEFT OUTER JOIN users ON users.id = transactions.seller_id 
         LEFT OUTER JOIN users buyers_transactions ON buyers_transactions.id = transactions.buyer_id 
         WHERE (`transactions`.`share1` IS NOT NULL) AND 
                    (`transactions`.`share2` IS NOT NULL) AND 
                    (`transactions`.`pictureBW` IS NOT NULL) AND 
                    (`transactions`.`pictureOriginal` IS NOT NULL) AND
                    (`transactions`.`recreatedPic` IS NOT NULL) AND 
                   `transactions`.`accepted` = 0 AND 
                   `transactions`.`rejected` = 0
) AS foo
```

The third one

``` sql
SELECT  transactions.id, amount, seller_id, buyer_id, users.email AS seller_email, buyers_transactions.email AS buyer_email 
FROM `transactions` 
LEFT OUTER JOIN users ON users.id = transactions.seller_id 
LEFT OUTER JOIN users buyers_transactions ON buyers_transactions.id = transactions.buyer_id 
WHERE (`transactions`.`share1` IS NOT NULL) AND 
           (`transactions`.`share2` IS NOT NULL) AND 
           (`transactions`.`pictureBW` IS NOT NULL) AND 
           (`transactions`.`pictureOriginal` IS NOT NULL) AND 
           (`transactions`.`recreatedPic` IS NOT NULL) AND 
          `transactions`.`accepted` = 0 AND 
          `transactions`.`rejected` = 0 
ORDER BY transactions.id ASC 
LIMIT 10 
OFFSET 0
```

**Comment by ajahongir** [comment]
@jmaggesi I see your problem. I guess you have to define your columns like here https://github.com/ajahongir/ajax-datatables-rails-v-0-4-0-how-to/blob/master/app/datatables/city_datatable.rb

if so, your columns will look like this:

``` ruby
  def view_columns
    @view_columns ||= {
      id: { source: 'Transaction.id', searchable: false, orderable: true, cond: :eq },
      seller: { source: 'seller_email', searchable: true, orderable: true, cond: filter_custom_field},
      buyer: { source: 'buyer_email', searchable: true, orderable: true, cond: filter_custom_field},
      amount: { source: 'Transaction.amount', searchable: false, orderable: true }
    }
  end
```

.....

``` ruby
def filter_custom_field
  ->(column) { ::Arel::Nodes::SqlLiteral.new(column.field.to_s).matches("#{ column.search.value }%") }
end
```

let me know if you will have any other issues.

**Comment by jmaggesi** [comment]
@ajahongir Thank you for your help, i've totally missed that part. Following your example i've changed a little bit the configuration and found a solution:

``` ruby
def view_columns
    @view_columns ||= {
      id: { source: 'Transaction.id', searchable: false, orderable: true, cond: :eq },
      seller: { source: 'seller_email', searchable: true, orderable: true, cond: filter_seller_email },
      buyer: { source: 'buyer_email', searchable: true, orderable: true , cond: filter_buyer_email },
      transactiontime: { source: 'Transaction.transactiontime', searchable: false, orderable: true },
      amount: { source: 'Transaction.amount', searchable: false, orderable: true }
    }
  end

```

.......

``` ruby
def filter_seller_email
    ->(column) { ::Arel::Nodes::SqlLiteral.new('users.email').matches("#{ column.search.value }%") }
  end

  def filter_buyer_email
    ->(column) { ::Arel::Nodes::SqlLiteral.new('buyers_transactions.email').matches("#{ column.search.value }%") }
  end
```

I've noticed that even if i set the columns like transactionstime and amount as non searchable columns the query generated includes the search even for those fields. It's supposed to be like that or am i missing something in the configuration ?

Maybe in the javascript part ? 

``` sql
SELECT  transactions.id, transactions.transactiontime, amount, seller_id, buyer_id, users.email AS seller_email, 
buyers_transactions.email AS buyer_email, accepted, rejected 
FROM `transactions` 
LEFT OUTER JOIN users ON users.id = transactions.seller_id 
LEFT OUTER JOIN users buyers_transactions ON buyers_transactions.id = transactions.buyer_id 
WHERE ((((`transactions`.`id` = 0 OR users.email LIKE 'sell%') OR buyers_transactions.email LIKE 'sell%') 
OR CAST(`transactions`.`transactiontime` AS CHAR) LIKE '%sell%') OR CAST(`transactions`.`amount` AS CHAR) LIKE '%sell%') 
ORDER BY transactions.id ASC LIMIT 10 OFFSET 0

```

**Comment by ajahongir** [comment]
> I've noticed that even if i set the columns like transactionstime and amount as non searchable columns the query generated includes the search even for those fields. It's supposed to be like that or am i missing something in the configuration ?
> 
> Maybe in the javascript part ?

yes you can turn on/off searching and ordering at datatable.js definition. for more details look at docs https://datatables.net/reference/option/columns.searchable

**Comment by jmaggesi** [comment]
Thank you, now works perfectly.
