### ISSUE TITLE
NoMethodError (undefined method `where' for #<Array:0x007fc56d301710>):

### ISSUE THREAD

**Issue by AdamMarkowski** [jbox-web/ajax-datatables-rails#28]
Hi!
It seems to doesn't works properly when there are scope that return an array, this is my config:

```
class StoreDatatable < AjaxDatatablesRails::Base
  # uncomment the appropriate paginator module,
  # depending on gems available in your project.
  # include AjaxDatatablesRails::Extensions::Kaminari
  include AjaxDatatablesRails::Extensions::WillPaginate
  # include AjaxDatatablesRails::Extensions::SimplePaginator

  def sortable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
    @sortable_columns = ['stores.name', 'stores.city', 'stores.street', 'stores.street_no']
  end

  def searchable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
    @searchable_columns = ['stores.name', 'stores.city', 'stores.street', 'stores.street_no']
  end

  private

  def data
    records.map do |record|
      [
        # comma separated list of the values for each cell of a table row
        # example: record.attribute,
      record.name,
      record.city,
      record.street,
      record.street_no
      ]
    end
  end

  def get_raw_records
    # insert query here
    Store.invalid_localization
  end

  # ==== Insert 'presenter'-like methods below if necessary
end
```

and the scope:

```
scope :invalid_localization, find_by_sql('SELECT *
                                            FROM stores
                                            WHERE NOT EXISTS
                                            (
                                                SELECT city_and_zips.city_name, city_and_zips.street, city_and_zips.province
                                                FROM city_and_zips
                                                WHERE city_and_zips.city_name != stores.city OR  city_and_zips.street != stores.street OR  city_and_zips.province != stores.province
                                            )')
```

It reports:

```
Completed 500 Internal Server Error in 20444.1ms

NoMethodError (undefined method `where' for #<Array:0x007f913e0b6ce8>):
  app/controllers/stores_controller.rb:261:in `block (2 levels) in index'
  app/controllers/stores_controller.rb:259:in `index'
```

Otherwise when get_raw_records is set just to Store without scope, everything works just fine.
Am I doing something wrong?

**Comment by antillas21** [comment]
Hi Adam,

Yes, you are right. I think I didn't document (or at least mention) this requirement in the README, but the result of the `get_raw_records` method **should** be an `ActiveRecord::Relation` object, in order to be able to chain the following methods on to it: `sort_records, filter_records, paginate_records`.

All these methods, will further filter down the resulting record set and play nicely to each other.

From what I see on your query to retrieve your results, you could make use of [Arel](https://github.com/rails/arel) in order to write the query as ruby (with the Arel syntax) and have a resulting `ActiveRecord::Relation` object.

Hope this helps you. Let me know if I can help on anything.

Antonio

**Comment by antillas21** [comment]
The requirement to return an `ActiveRecord::Relation` object has been documented. You can take a look here: https://github.com/antillas21/ajax-datatables-rails#get-raw-records.

Thanks for bringing this to our attention :smile:
