### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by gipdiaz** [jbox-web/ajax-datatables-rails#30]
Hi,

I'm trying to use your gem with my project. I had install "jquery-datatable-rails" gem and I need to add to the query through AJAX. My model is "Establecimiento".

My code

establecimiento_datatable.rb

``` ruby
class EstablecimientoDatatable < AjaxDatatablesRails::Base
  include AjaxDatatablesRails::Extensions::Kaminari

  def sortable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
    @sortable_columns ||= ['establecimientos.cue']
  end

  def searchable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
    @searchable_columns ||= []
  end

  private

  def data
    records.map do |record|
      [
        record.cue
      ]
    end
  end

  def get_raw_records
    Establecimiento.all
  end

end
```

establecimientos_controller.rb

``` ruby
  def index
    @establecimientos = EstablecimientoDatatable.new(view_context)
    respond_to do |format|
      format.html
      format.json { render json: @establecimientos }
    end
  end
```

index.html.erb

``` html+erb
<div class="table-responsive">
  <table id="tabla-establecimiento" class="table table-striped table-bordered table-hover" data-source="<%= establecimientos_path(format: :json) %>">
    <thead>
      <tr>
        <th>Cue</th>    
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

<script type="text/javascript">
    $(document).ready(function($) {
      $('#tabla-establecimiento').dataTable({
        "oLanguage": {"sUrl": "assets/language.es.json",},
        "processing": true,
        "serverSide": true,
        "sAjaxSource": $('#tabla-establecimiento').data('source')
      });
    });
</script>
```

Error

```
undefined method `[]' for nil:NilClass

app/datatables/establecimiento_datatable.rb:23:in `data'
app/controllers/establecimientos_controller.rb:10:in `block (2 levels) in index'
app/controllers/establecimientos_controller.rb:8:in `index'
```

I search in google for many sites and didnt get any solution for this error, hope you can help me and very good job with this project.

Sorry for my english, Greetings from Argentina!!

**Comment by antillas21** [comment]
Hola Gastón,

No te preocupes por tu Inglés. Voy a cambiar a Español para que sea más entendible mi respuesta :smile:

Lo que veo en tu código, es que estás instanciando la clase de `EstablecimientoDatatable` fuera del scope que necesitas. En tu controlador tienes lo siguiente:

``` ruby
# app/controllers/establecimientos_controller.rb
def index
    # instanciar esto aquí, puede causar el error
    @establecimientos = EstablecimientoDatatable.new(view_context)
    respond_to do |format|
      format.html
      format.json { render json: @establecimientos }
    end
  end
```

Cuando debería ser:

``` ruby
# app/controllers/establecimientos_controller.rb
def index
    respond_to do |format|
      format.html
      format.json { render json: EstablecimientoDatatable.new(view_context) }
    end
  end
```

Sé que a simple vista parece igual y que solo moví la línea de lugar, pero según las convenciones de Rails, no es lo mismo.

En esta versión, estoy diciendole a Rails que en la vista en formato html (la que se renderea cuando vaya a la ruta `/establecimientos`) no tendrá ninguna variable de instancia creada ni cualquier otra acción que pueda causar molestias.

También, tu clase `EstablecimientoDatatable` debe contener al menos una columna en el array del método `searchable_columns` o en su defecto, agrega al código de jquery que activa el plugin, la especificación de cuales columnas serán "searchable". Ejemplo:

``` javascript
    $(document).ready(function($) {
      $('#tabla-establecimiento').dataTable({
        "oLanguage": {"sUrl": "assets/language.es.json",},
        "processing": true,
        "serverSide": true,
        "sAjaxSource": $('#tabla-establecimiento').data('source'),
        "columns": [
            { "sortable": false, "searchable": false },
            { "sortable": true, "searchable": false }
         ]
      });
    });
```

Espero esto te ayude a resolver el problema que tienes.

**Comment by antillas21** [comment]
Ooh, acabo de darme cuenta que cuando agregué código al ejemplo de jQuery en mi comentario anterior, usé la sintaxis de la versión más reciente de jQuery.dataTables (ver. 1.10), cuando tú estás usando la versión 1.9 del mismo.

La idea es la misma, solo la sintaxis cambia... si mal no recuerdo, para esa versión, aplica algo como:

``` javascript
$(document).ready(function($) {
      $('#tabla-establecimiento').dataTable({
        "oLanguage": {"sUrl": "assets/language.es.json",},
        "processing": true,
        "serverSide": true,
        "sAjaxSource": $('#tabla-establecimiento').data('source'),
        "aoColumns": [
            { "bSortable" : false, "bSearchable" : false },
            { "bSortable": true, "bSearchable" : false },
      });
});
```

Espero haberlo hecho bien esta vez :-)

Saludos desde México.

**Comment by gipdiaz** [comment]
Hola Antonio,

Gracias por la pronta respuesta. El cambio en el controller lo había hecho mientras probada distintas cosas para que funcione, por lo cual lo deje como antes y sigo con el mismo problema.

Con respecto a las versiones de las gemas, estuve mirando y estaba usando lo siguiente:
- jquery-datatables-rails 1.12.2 (usa datatable 1.9)
- ajax-datatables-rails 0.2.0 (usa datatable 1.10)
- rails 3.2.8
- jquery-rails 2.3.0

Lo que hice fue instalar la version 0.1.2 de tu gema y quedo de la siguiente manera:

establecimiento_datatable.rb

``` ruby
class EstablecimientoDatatable < AjaxDatatablesRails::Base
  include AjaxDatatablesRails::Extensions::Kaminari

  def sortable_columns
    @sortable_columns ||= ['establecimientos.cue']
  end

  def searchable_columns
    @searchable_columns ||= ['establecimientos.cue']
  end

  private

  def data
    records.map do |record|
      [
        record.cue
      ]
    end
  end

  def get_raw_records
    Establecimiento.all
  end

end
```

index.html.erb

``` html+erb
<div class="table-responsive">
  <table id="tabla-establecimiento" class="table table-striped table-bordered table-hover" data-source="<%= establecimientos_path(format: :json) %>">
    <thead>
      <tr>
        <th>Cue</th>    
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

<script type="text/javascript">
    $(document).ready(function($) {
      $('#tabla-establecimiento').dataTable({
        "oLanguage": {"sUrl": "assets/language.es.json",},
        "processing": true,
        "serverSide": true,
        "sAjaxSource": $('#tabla-establecimiento').data('source'),
        "aoColumns": [
          { "bSortable" : false, "bSearchable" : false },
        ]
      });
    });
</script>
```

establecimientos_controller.rb

``` ruby
def index
    respond_to do |format|
      format.html
      format.json { render json: EstablecimientoDatatable.new(view_context) }
    end
  end
```

Con el cambio de la versión de tu gema y en el código ahora tengo el siguiente error:

```
NoMethodError in EstablecimientosController#index
undefined method `order' for #<Array:0xb4bdc84c>
```

Application Trace

```
app/datatables/establecimiento_datatable.rb:15:in `data'
app/controllers/establecimientos_controller.rb:9:in `block (2 levels) in index'
app/controllers/establecimientos_controller.rb:7:in `index'
```

Full Trace

```
ajax-datatables-rails (0.1.2) lib/ajax-datatables-rails/base.rb:60:in `sort_records'
ajax-datatables-rails (0.1.2) lib/ajax-datatables-rails/base.rb:53:in `fetch_records'
ajax-datatables-rails (0.1.2) lib/ajax-datatables-rails/base.rb:48:in `records'
app/datatables/establecimiento_datatable.rb:15:in `data'
ajax-datatables-rails (0.1.2) lib/ajax-datatables-rails/base.rb:41:in `as_json'
activesupport (3.2.8) lib/active_support/json/encoding.rb:47:in `block in encode'
activesupport (3.2.8) lib/active_support/json/encoding.rb:77:in `check_for_circular_references'
activesupport (3.2.8) lib/active_support/json/encoding.rb:46:in `encode'
activesupport (3.2.8) lib/active_support/json/encoding.rb:31:in `encode'
activesupport (3.2.8) lib/active_support/core_ext/object/to_json.rb:16:in `to_json'
actionpack (3.2.8) lib/action_controller/metal/renderers.rb:93:in `block in <module:Renderers>'
actionpack (3.2.8) lib/action_controller/metal/renderers.rb:35:in `block in _handle_render_options'
/home/pregase01/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/set.rb:222:in `block in each'
/home/pregase01/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/set.rb:222:in `each_key'
/home/pregase01/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/set.rb:222:in `each'
actionpack (3.2.8) lib/action_controller/metal/renderers.rb:32:in `_handle_render_options'
actionpack (3.2.8) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
actionpack (3.2.8) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
actionpack (3.2.8) lib/abstract_controller/rendering.rb:88:in `render'
actionpack (3.2.8) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.2.8) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/home/pregase01/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
activesupport (3.2.8) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
activerecord (3.2.8) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:39:in `render'
remotipart (1.2.1) lib/remotipart/render_overrides.rb:14:in `render_with_remotipart'
app/controllers/establecimientos_controller.rb:9:in `block (2 levels) in index'
actionpack (3.2.8) lib/action_controller/metal/mime_responds.rb:196:in `call'
actionpack (3.2.8) lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
app/controllers/establecimientos_controller.rb:7:in `index'
actionpack (3.2.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.8) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.8) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.8) lib/active_support/callbacks.rb:436:in `_run__878328604__process_action__768652072__callbacks'
activesupport (3.2.8) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.8) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.8) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.8) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.8) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.8) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.2.8) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.8) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.8) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.8) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.8) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:600:in `call'
rack-pjax (0.7.0) lib/rack/pjax.rb:12:in `call'
pdfkit (0.6.2) lib/pdfkit/middleware.rb:17:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
actionpack (3.2.8) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.5) lib/rack/etag.rb:23:in `call'
rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.8) lib/action_dispatch/middleware/head.rb:14:in `call'
remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
actionpack (3.2.8) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.8) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.8) lib/action_dispatch/middleware/cookies.rb:339:in `call'
activerecord (3.2.8) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `call'
actionpack (3.2.8) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.8) lib/active_support/callbacks.rb:405:in `_run__537501855__call__29963130__callbacks'
activesupport (3.2.8) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.8) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.8) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.8) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.8) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.8) lib/rails/rack/logger.rb:26:in `call_app'
railties (3.2.8) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.8) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.5) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.8) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
actionpack (3.2.8) lib/action_dispatch/middleware/static.rb:62:in `call'
railties (3.2.8) lib/rails/engine.rb:479:in `call'
railties (3.2.8) lib/rails/application.rb:223:in `call'
rack (1.4.5) lib/rack/content_length.rb:14:in `call'
railties (3.2.8) lib/rails/rack/debugger.rb:20:in `call'
railties (3.2.8) lib/rails/rack/log_tailer.rb:17:in `call'
rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
/home/pregase01/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
/home/pregase01/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
/home/pregase01/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

El error surge en la estructura records dentro del método data.

Desde ya muchas gracias!

**Comment by antillas21** [comment]
Hola Gastón,

Este error:

```
NoMethodError in EstablecimientosController#index
undefined method `order' for #<Array:0xb4bdc84c>
```

Es porque el resultado del método `get_raw_records` te está regresando un `Array` y no un `ActiveRecord::Relation` que es lo que espera para encadenarlo a los métodos de `sort_records, filter_records, paginate_records`.

[Este otro issue](https://github.com/antillas21/ajax-datatables-rails/issues/28) tiene ese mismo problema. La solución es la misma: asegúrate que el resultado de `get_raw_records` sea un `ActiveRecord::Relation`.

Si ahora tienes:

``` ruby
def get_raw_records
  Establecimiento.all
end
```

Y regresa un Array, puedo interpretar que estás en Rails <= 3.x.

**Comment by antillas21** [comment]
Hice unas pruebas en un proyecto que usa Rails 3.0.x (no preguntes por qué esa versión)

Y obtuve esto:

``` ruby
User.all.class
#=> Array

User.scoped.class
#=> ActiveRecord::Relation

User.unscoped.class
#=> ActiveRecord::Relation
```

Mi recomendación es que uses `Establecimiento.unscoped` como query dentro del método `get_raw_records`.

De esta manera ActiveRecord va a consultar todos los registros de la tabla sin aplicar ningún scope o filtro, regresará un objeto de tipo `ActiveRecord::Relation` que es lo que necesita la clase `AjaxDatatablesRails::Base` de la cual hereda tu clase `EstablecimientoDatatable` para continuar con aplicarle orden, filtro y paginado.

**Comment by antillas21** [comment]
Y gracias al issue que te mencioné (y ahora tu caso) decidí mencionar esto en el README: https://github.com/antillas21/ajax-datatables-rails#get-raw-records

**Comment by gipdiaz** [comment]
Muchas Gracias Antonio!

Ya pude hacerlo funcionar cambiando las cosas que me indicaste. Ahora el tema es que solo me muestra 10 registros y 1 sola página.

En el JSON se ve que la cantidad total de registros son 1169.

```
{"sEcho":0,"iTotalRecords":1169,"iTotalDisplayRecords":1169,"aaData":[["0","EFOCAPEMM - Comodoro Rivadavia"],["0","EFOCAPEMM - Puerto Madryn"],["0","EFOCAPEMM - Rawson"],["1","PATAGONIA ARGENTINA"],["1","PATAGONIA ARGENTINA"],["10","MARTIN MIGUEL DE G\u00dcEMES"],["10","MARTIN MIGUEL DE G\u00dcEMES"],["100","BARTOLOM\u00c9 MITRE"],["100","BARTOLOM\u00c9 MITRE"],["10001","Intituto P\u00fablico y Privado"]]}
```

El js me quedo de la siguiente forma:

``` html
<script type="text/javascript">
    $(document).ready(function($) {
      $('#tabla-establecimiento').dataTable({
        "oLanguage": {"sUrl": "assets/language.es.json",},
        "processing": true,
        "serverSide": true,
        "sAjaxSource": $('#tabla-establecimiento').data('source'),
        "sPaginationType": "full_numbers",
        //"sPaginationType": "bootstrap",
      });
    });
</script>
```

[Captura de Pantalla](http://postimg.org/image/tepyzmbtr/)

Cambie a Will Paginate porque Kaminari me daba un error.

Gracias por todo Antonio!

**Comment by gipdiaz** [comment]
Ya lo solucione, el error era en la sintaxis que me indicaste antes en el js.

``` html
<script type="text/javascript">
    $(document).ready(function($) {
      $('#tabla-establecimiento').dataTable({
        "oLanguage": {"sUrl": "assets/language.es.json",},
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": $('#tabla-establecimiento').data('source'),
        "sPaginationType": "full_numbers",
      });
    });
</script>
```

Muchisimas Gracias!!

**Comment by antillas21** [comment]
Excelente Gastón!

Sobre `WillPaginate` o `Kaminari`, debes descomentar la línea de acuerdo a qué librería estás usando en tu proyecto.

Si no estás usando ninguna, o no quieres que `Kaminari` o `WillPaginate` se hagan cargo de paginar los registros, descomenta la línea de `SimplePaginator`. Esta extensión va directo a la base de datos y usa `ActiveRecord`.

Pues creo que con esto cerramos tu caso. Espero te sea de utilidad esta pequeña gema y aligere tu trabajo de ahora en adelante :smile:

**Comment by capitillol** [comment]
Buenos Dias, estoy tratando de revisar cada parte del codigo y no encuentro la falla me esta generando este error necesito ayuda para poder continuar con las tareas

irb(main):001:0> p[0].destroy

NoMethodError: undefined method `[]' for nil:NilClass

este error me genera al realizar la interacion #2 de la aplicación BLOG, no puedo conseguir eliminar ninguna post de la aplicacion

espero me puedan ayudar soy nuevo utilizando esta programación
