### ISSUE TITLE
NameError (undefined local variable or method `fetch_records' for #<ForumsDatatable:0x00007ff21c1decf8>):

### ISSUE THREAD

**Issue by ghost** [jbox-web/ajax-datatables-rails#316]
I have an issue with base.rb = 

```
NameError (undefined local variable or method `fetch_records' for #<ForumsDatatable:0x00007ff21c1decf8>):
undefined local variable or method `fetch_records' for #<ForumsDatatable:0x00007f8f60d48b58>
Extracted source (around line #103):

#101 
#102     def records_total_count
*103       fetch_records.count(:all)
#104     end
#105 
#106     def records_filtered_count

Extracted source (around line #34):

#32     def as_json(*)
#33       {
*34         recordsTotal:    records_total_count,
#35         recordsFiltered: records_filtered_count,
#36         data:            sanitize(data)
#37       }.merge(get_additional_data)

Extracted source (around line #35):

#33         # Encode the given object into a JSON string
#34         def encode(value)
*35           stringify jsonify value.as_json(options.dup)
#36         end
#37 
#38         private


Rails.root: /Users/xxx/Documents/xxx/coursesocial.rocks

Application Trace
app/controllers/admin_controller.rb:62:in `block (2 levels) in forums'
app/controllers/admin_controller.rb:60:in `forums'

Framework Trace
ajax-datatables-rails (1.0.0) lib/ajax-datatables-rails/base.rb:103:in `records_total_count'
ajax-datatables-rails (1.0.0) lib/ajax-datatables-rails/base.rb:34:in `as_json'
```

**Comment by n-rodriguez** [comment]
https://github.com/jbox-web/ajax-datatables-rails/blob/master/doc/migrate.md
