### ISSUE TITLE
searchable_columns and quoted column names problem

### ISSUE THREAD

**Issue by OndroNR** [jbox-web/ajax-datatables-rails#33]
Hi, I am building Rails app on top of legacy database, which I cannot alter at this time.

When I have `@searchable_columns ||= ["\"UserProfile\".\"UserId\""]`, I get following error:

```
NameError (wrong constant name "UserProfile"):
  app/controllers/admin/users_controller.rb:7:in `block (2 levels) in index'
  app/controllers/admin/users_controller.rb:5:in `index'
```

It fails in `.constantize` in line `model = model.singularize.titleize.gsub( / /, '' ).constantize`

**Comment by OndroNR** [comment]
Closing, it generates correct column name, when I ommit `\"` and fails on issue #27 :)
