### ISSUE TITLE
Version 1.3.0 breaks Ruby on Rails application? (undefined method `configure' for AjaxDatatablesRails:Module)

### ISSUE THREAD

**Issue by altjx** [jbox-web/ajax-datatables-rails#378]
Just pushed out changes to my Rails application, which always runs a bundle install, and turns out I can no longer run Sidekiq as the application is erroring out.

My Gemfile includes `ajax-datatables-rails`. The dev application works fine when using version 1.2.0, but for whatever reason 1.3.0 breaks the app.

```
root@706a33be0f2a:/myapp# bundle exec sidekiq -e production -q production
2021-01-05T00:50:16.034Z pid=197 tid=gq2gcjz7p WARN: NoMethodError: undefined method `configure' for AjaxDatatablesRails:Module
2021-01-05T00:50:16.034Z pid=197 tid=gq2gcjz7p WARN: /myapp/config/initializers/ajax_datatables_rails.rb:3:in `<top (required)>'
/usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/usr/local/bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:285:in `block in load'
/usr/local/bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/engine.rb:663:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-5.2.4/lib/active_support/notifications.rb:170:in `instrument'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/engine.rb:662:in `load_config_initializer'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/engine.rb:619:in `each'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/engine.rb:619:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/initializable.rb:50:in `each'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/local/lib/ruby/2.5.0/tsort.rb:415:in `call'
/usr/local/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/application.rb:361:in `initialize!'
/myapp/config/environment.rb:7:in `<top (required)>'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/cli.rb:252:in `require'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/cli.rb:252:in `boot_application'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/cli.rb:37:in `run'
/usr/local/bundle/gems/sidekiq-6.1.2/bin/sidekiq:31:in `<top (required)>'
/usr/local/bundle/bin/sidekiq:23:in `load'
/usr/local/bundle/bin/sidekiq:23:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/bin/bundle:22:in `<main>'
```

I've confirmed that going back down to version 1.2.0 fixes the problem.

**Comment by n-rodriguez** [comment]
https://github.com/jbox-web/ajax-datatables-rails/blob/master/CHANGELOG.md

**Comment by hemanthguptha** [comment]
Try this 
Root_Directory/config/environment/development.rb

Change this line
Rails.application.configure do
To
Rails_Application_Folder_name::Application.configure do

**Comment by n-rodriguez** [comment]
@hemanthguptha nope. See the changelog.
