### ISSUE TITLE
NoMethodError: undefined method `configure' for AjaxDatatablesRails:Module- rails 4.2.11.1

### ISSUE THREAD

**Issue by vijay-zensar** [jbox-web/ajax-datatables-rails#416]
My application is running on rails version 4.2.11.1. while using **gem 'ajax-datatables-rails', '~> 1.3.0',** I got the below error

```
NoMethodError: undefined method `configure' for AjaxDatatablesRails:Module
/home/vijay/ICANN/rails-atlarge/config/initializers/ajax_datatables_rails.rb:1:in `<top (required)>'
/home/vijay/ICANN/rails-atlarge/config/environment.rb:5:in `<top (required)>

```
Now I have changed gem version **gem 'ajax-datatables-rails', '~> 1.0.0'** then get bolow error.
```
uninitialized constant AjaxDatatablesRails::Extensions
22:44:00 worker.1 | /home/vijay/ICANN/rails-atlarge/app/datatables/admin/at_large_structures_datatable.rb:3:in `<class:AtLargeStructuresDatatable>'
22:44:00 worker.1 | /home/vijay/ICANN/rails-atlarge/app/datatables/admin/at_large_structures_datatable.rb:1:in `<top (required)>
```
Please help me to fix this issue. Thanks

**Comment by n-rodriguez** [comment]
https://github.com/jbox-web/ajax-datatables-rails/blob/master/doc/migrate.md#to-migrate-from-v1x-to-v130
