### ISSUE TITLE
Error when trying to create Searchable columns syntax

### ISSUE THREAD

**Issue by iamspauljamez** [jbox-web/ajax-datatables-rails#79]
Hello, 

When I've put searchable items in the array like this:

```
def searchable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
    @searchable_columns ||= ['requests.type' , 'requests.status', 'Client.first_name']
  end
```

after reloading page the table runs and suddenly I do search, I've got some search and my output is this:

```
ActiveRecord::StatementInvalid (Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VARCHAR) LIKE '%sa%' OR CAST(`requests`.`status` AS VARCHAR) LIKE '%sa%') OR CAS' at line 1: SELECT COUNT(*) FROM `requests`  WHERE `requests`.`deleted_at` IS NULL AND (request_to_id = 1002 OR created_by_id = 1002) AND (((CAST(`requests`.`type` AS VARCHAR) LIKE '%sa%' OR CAST(`requests`.`status` AS VARCHAR) LIKE '%sa%') OR CAST(`clients`.`first_name` AS VARCHAR) LIKE '%sa%'))):
  app/controllers/requests_controller.rb:107:in `block (2 levels) in request_list'
  app/controllers/requests_controller.rb:105:in `request_list'

```

Hope you could help me. Thanks.

**Comment by ArunSakthivel** [comment]
You need to give "sortable_columns" values also, For example
def sortable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
    @sortable_columns ||= ['requests.type' , 'requests.status']
  end

**Comment by antillas21** [comment]
@Iamspauljamez18 , could you please confirm the content of the `sortable_columns` method?

Also, the comments I see in your `searchable_columns` method, are from the previous version of the gem (`0.2.x`), while you are declaring some columns using the new gem version's syntax, visible on `Client.first_name` as opposed to `requests.status`.

**Comment by iamspauljamez** [comment]
@antillas21 , I've updated the gem to 0.3.0. That's why you see comment from the previous version. 
Here's my sortable columns.

```
  def sortable_columns
    # list columns inside the Array in string dot notation.
    # Example: 'users.email'
    @sortable_columns ||= ['requests.type', 'requests.status', 'Client.first_name']
  end
```

^ I've made my sortable_columns and searchable_columns the same.

**Comment by antillas21** [comment]
@Iamspauljamez18 I see that you're using `MySQL`... have you added the initializer file to declare that the `:db_adapter` to use is `:mysql2`? Instructions here: https://github.com/antillas21/ajax-datatables-rails#configuration-initializer

Why an initializer you may ask?

Well, if you read this section in the `README` file: https://github.com/antillas21/ajax-datatables-rails#searching-on-non-text-based-columns you'll notice that the gem assumes you are using `postgresql` as your db engine... if it's not, then you should specify the engine, to retrieve the proper `typecast` when building an SQL query, see this method for reference: https://github.com/antillas21/ajax-datatables-rails/blob/master/lib/ajax-datatables-rails/base.rb#L148-L154

**Comment by iamspauljamez** [comment]
@antillas21 , Thanks. It works man.

**Comment by bliaxiong** [comment]
I'm having the same issue. Using Ruby 2.2.3, Rails 4.2.4, mysql2 gem and ajax-datatables-jquery 0.3.1. Totally lost as to why its not working. Any help/suggestions appreciated.

``` Ruby
  def searchable_columns
    @searchable_columns ||= ['Treatment.name', 'Treatment.description', 'Treatment.price', 'Treatment.code']
  end
```

Init file:

``` Ruby
AjaxDatatablesRails.config do |config|
  config.db_adaptor = :mysql2
  config.paginator = :Kaminari
end 
```

JS:

``` javascript
  $("#treatment_list").DataTable({
    reponsive: true,
    autoFill: true,
    fixHeader: true,
    ajax: $("#treatment_list").data("source"),
    autoWidth: true,
    pagingType: 'simple_numbers',
    processing: true,
    serverSide: true
    columnDefs: [{orderable: false, targets: [1]}] 
  });
```

**Comment by antillas21** [comment]
you may have a typo on `.db_adaptor`, it should be `.db_adapter`, I think.

**Comment by bliaxiong** [comment]
Fixed. Still have an issue.

**Comment by ajahongir** [comment]
@bliaxiong can you show an error message?

**Comment by bliaxiong** [comment]
This is the error stack trace:

``` Ruby
Started GET "/clinics/1/claims.json?draw=2&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=b&search%5Bregex%5D=false&_=1450483603481" for 127.0.0.1 at 2015-12-18 18:06:50 -0600
Processing by ClaimsController#index as JSON
  Parameters: {"draw"=>"2", "columns"=>{"0"=>{"data"=>"0", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "1"=>{"data"=>"1", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "2"=>{"data"=>"2", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "3"=>{"data"=>"3", "name"=>"", "searchable"=>"true", "orderable"=>"false", "search"=>{"value"=>"", "regex"=>"false"}}, "4"=>{"data"=>"4", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "5"=>{"data"=>"5", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}}, "order"=>{"0"=>{"column"=>"0", "dir"=>"asc"}}, "start"=>"0", "length"=>"10", "search"=>{"value"=>"b", "regex"=>"false"}, "_"=>"1450483603481", "clinic_id"=>"1"}
  User Load (0.5ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 6  ORDER BY `users`.`id` ASC LIMIT 1
   (0.4ms)  SELECT COUNT(*) FROM `claims` WHERE `claims`.`clinic_id` = 1
   (2.0ms)  SELECT COUNT(*) FROM `claims` WHERE `claims`.`clinic_id` = 1 AND (((CAST(`claims`.`amount` AS VARCHAR) LIKE '%b%' OR CAST(`claims`.`processed` AS VARCHAR) LIKE '%b%') OR CAST(`claims`.`failed` AS VARCHAR) LIKE '%b%') OR CAST(`claims`.`appointment_id` AS VARCHAR) LIKE '%b%')
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VARCHAR) LIKE '%b%' OR CAST(`claims`.`processed` AS VARCHAR) LIKE '%b%') OR CAST' at line 1: SELECT COUNT(*) FROM `claims` WHERE `claims`.`clinic_id` = 1 AND (((CAST(`claims`.`amount` AS VARCHAR) LIKE '%b%' OR CAST(`claims`.`processed` AS VARCHAR) LIKE '%b%') OR CAST(`claims`.`failed` AS VARCHAR) LIKE '%b%') OR CAST(`claims`.`appointment_id` AS VARCHAR) LIKE '%b%')
Completed 500 Internal Server Error in 14ms (ActiveRecord: 2.8ms)

Mysql2::Error - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VARCHAR) LIKE '%b%' OR CAST(`claims`.`processed` AS VARCHAR) LIKE '%b%') OR CAST' at line 1:
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
  activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
  activerecord (4.2.4) lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
  activerecord (4.2.4) lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `exec_query'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/database_statements.rb:351:in `select'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
  activerecord (4.2.4) lib/active_record/relation/calculations.rb:264:in `execute_simple_calculation'
  activerecord (4.2.4) lib/active_record/relation/calculations.rb:221:in `perform_calculation'
  activerecord (4.2.4) lib/active_record/relation/calculations.rb:127:in `calculate'
  activerecord (4.2.4) lib/active_record/relation/calculations.rb:42:in `count'
  ajax-datatables-rails (0.3.1) lib/ajax-datatables-rails/base.rb:45:in `as_json'
  activesupport (4.2.4) lib/active_support/json/encoding.rb:35:in `encode'
  activesupport (4.2.4) lib/active_support/json/encoding.rb:22:in `encode'
  activesupport (4.2.4) lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
  actionpack (4.2.4) lib/action_controller/metal/renderers.rb:116:in `block in <module:Renderers>'
  actionpack (4.2.4) lib/action_controller/metal/renderers.rb:45:in `block in _render_to_body_with_renderer'
  /home/blia/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/set.rb:283:in `each'
  actionpack (4.2.4) lib/action_controller/metal/renderers.rb:41:in `_render_to_body_with_renderer'
  actionpack (4.2.4) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.4) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.4) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.4) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/blia/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.4) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.4) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:43:in `render'
  app/controllers/claims_controller.rb:10:in `block (2 levels) in index'
  actionpack (4.2.4) lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
  app/controllers/claims_controller.rb:8:in `index'
  actionpack (4.2.4) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.4) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.4) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.4) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.4) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.4) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.4) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
  warden (1.2.4) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.4) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.4) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.4) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  request_store (1.2.1) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.4) lib/thin/connection.rb:53:in `process'
  thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.8) lib/eventmachine.rb:193:in `run'
  thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.4) lib/thin/server.rb:162:in `start'
  rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.4) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.4) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.4) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.4) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.4) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `<main>'
```

**Comment by ajahongir** [comment]
@bliaxiong 

> ``` ruby
> AjaxDatatablesRails.config do |config|
>   config.db_adaptor = :mysql2
>   config.paginator = :Kaminari
> end 
> ```
> 
> try to change:
> 
> ``` ruby
> AjaxDatatablesRails.configure do |config|
>   config.db_adapter = :mysql2
>   config.paginator = :Kaminari
> end
> ```
