### ISSUE TITLE
Issue with joins with a where clause on Rails 4.2

### ISSUE THREAD

**Issue by iamkobold** [jbox-web/ajax-datatables-rails#90]
The following code produces the following error Cannot visit ParentModel::ActiveRecord_Relation from the looks of it, it seems like the error happens when converting the DataTable object to JSON.

``` ruby
def get_raw_records
 ParentModel.where(x: 1).joins(:child).where(y: 1, z: 2)
end
```

My ParentModel has a _has_one_ _child_ that is declared via the joins() method and i am actually applying a where clause on the join to reduce/search on the child per the Rails guide http://guides.rubyonrails.org/active_record_querying.html#specifying-conditions-on-the-joined-tables 

stack trace is as follows if this helps

```
gems/arel-6.0.0/lib/arel/visitors/visitor.rb:35:in `rescue in visit'
gems/arel-6.0.0/lib/arel/visitors/visitor.rb:29:in `visit'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:12:in `visit'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:17:in `unary'
gems/arel-6.0.0/lib/arel/visitors/visitor.rb:29:in `visit'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:12:in `visit'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:57:in `block in nary'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:57:in `each'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:57:in `nary'
gems/arel-6.0.0/lib/arel/visitors/visitor.rb:29:in `visit'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:12:in `visit'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:169:in `block in visit_Array'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:169:in `each'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:169:in `visit_Array'
gems/arel-6.0.0/lib/arel/visitors/visitor.rb:29:in `visit'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:12:in `visit'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:146:in `visit_Arel_Nodes_SelectCore'
gems/arel-6.0.0/lib/arel/visitors/visitor.rb:29:in `visit'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:12:in `visit'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:169:in `block in visit_Array'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:169:in `each'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:169:in `visit_Array'
gems/arel-6.0.0/lib/arel/visitors/visitor.rb:29:in `visit'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:12:in `visit'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:153:in `visit_Arel_Nodes_SelectStatement'
gems/arel-6.0.0/lib/arel/visitors/visitor.rb:29:in `visit'
gems/arel-6.0.0/lib/arel/visitors/depth_first.rb:12:in `visit'
gems/arel-6.0.0/lib/arel/visitors/visitor.rb:9:in `accept'
gems/arel-6.0.0/lib/arel/nodes/node.rb:56:in `each'
gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb:210:in `grep'
gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb:210:in `perform_calculation'
gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb:127:in `calculate'
gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb:42:in `count'
gems/ajax-datatables-rails-0.3.0/lib/ajax-datatables-rails/base.rb:44:in `as_json'
gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:34:in `encode'
gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:21:in `encode'
gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:116:in `block in <module:Renderers>'
gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:45:in `block in _render_to_body_with_renderer'
.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/set.rb:263:in `each_key'
.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/set.rb:263:in `each'
gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:41:in `_render_to_body_with_renderer'
gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
gems/actionpack-4.2.0/lib/abstract_controller/rendering.rb:25:in `render'
gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:16:in `render'
gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
gems/activesupport-4.2.0/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
gems/activesupport-4.2.0/lib/active_support/core_ext/benchmark.rb:12:in `ms'
gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:40:in `render'
```

**Comment by antillas21** [comment]
@iamkobold From your example, I think this is what works, from my experience with `ActiveRecord`

``` ruby
# models:
# parent => Client
# child => Address
# relationship: Client has_one Address

# join child model and filter by a value on parent
Client.joins(:address).where(active: true)

# join child model and filter by a value on child
Client.joins(:address).where(addresses: { city: 'Los Angeles' })

# join child model and filter by a value on parent and child
Client.joins(:address).where(active: true, addresses: { city: 'San Diego' })
```

please notice how when you need to filter by a value in the child model, you use the table name of the child model as key in the `where` hash.

So, basically you construct queries like this:

``` ruby
Model.joins(:related_model)
  .where(attribute: 'value', related_model_table: { related_model_attribute: 'value'} )
```

**Comment by iamkobold** [comment]
OK, i wouldn't be surprised if i was doing something incorrect. It was just a bit confusing since the function returns the right ParentModel rows as I would expect them to. So why it wasn't working with the JSON marshaling was annoying. 

I will try your suggestion though and see how it works. Thanks for the pointer.

**Comment by iamkobold** [comment]
So I modified my query as suggested and it still gives me the same error with not being able to visit ParentModel::ActiveRecord_Relation. Is this actually a bug possibly in AREL ? 

Because the SQL that ActiveRecord is generating is exactly what I would expect

> ParentModel.joins(:children).where(foo: 'x', bar: 0, children: {baz: 0}) 
> 
> ``` sql
> SELECT `parent_models`.* FROM `parent_models` 
>     INNER JOIN `children` ON `children`.`parent_model_id` = `children`.`id` 
> WHERE `parent_model`.`x` = 'foo' AND `parent_model`.`bar` = 0 AND `children`.`baz` = 0
> ```

**Comment by iamkobold** [comment]
Wait, never mind this was my error i just found that i had the ParentModel.where(ParentModel.joins(:children).where()) so that would explain the AREL errors now. 

Thanks for the tip though, and sorry for the issues.

**Comment by antillas21** [comment]
Don't worry. Glad you could solve your issue.
